### ISSUE TITLE
Definir a paleta de cores do site

### ISSUE THREAD

**Issue by natan-fernandes** [UniAcademia/Lupa-Mutirao#3]
Vamos definir a paleta de cores do site do Lupa nesse issue!

**Comment by natan-fernandes** [comment]
Eu pensei em fazer o site predominantemente em preto e branco e para isso utilizaria o **coolors.co** para gerar uma paleta baseada nessas cores, se alguém tiver alguma sugestão de outro site para fazer a paleta seria uma boa.

Nesse link aqui tem instruções de como trabalhar com cores:
[https://material.io/design/color/the-color-system.html#color-theme-creation](url)

**Comment by Carlosalb8** [comment]
Muito massa, não sabia desse site!!

**Comment by natan-fernandes** [comment]
Foi definido que será utilizado predominantemente as cores preto e branco
